name: Docs WorkFlow - Develop Tag 📚

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pages: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: 📦 Install mkdocs-material
        run: pip install mkdocs-material
      - name: 📦 Install mkdocstrings[python]
        run: pip install "mkdocstrings[python]"
      - name: 📦 Install mkdocs-material[imaging]
        run: pip install "mkdocs-material[imaging]"
      - name: 📦 Install mike
        run: pip install "mike"
      - name: ⚙️ Configure git for github-actions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: 🚀 Deploy MkDoc-Material with mike
        run: |
          mike deploy --push develop
